package cn.scau.pojo;

public class DailyStatus extends DailyStatusKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DailyStatus.sold
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	private Integer sold;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DailyStatus.other
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	private Integer other;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DailyStatus.refRule
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	private Integer refRule;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DailyStatus.sold
	 * @return  the value of DailyStatus.sold
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public Integer getSold() {
		return sold;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DailyStatus.sold
	 * @param sold  the value for DailyStatus.sold
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public void setSold(Integer sold) {
		this.sold = sold;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DailyStatus.other
	 * @return  the value of DailyStatus.other
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public Integer getOther() {
		return other;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DailyStatus.other
	 * @param other  the value for DailyStatus.other
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public void setOther(Integer other) {
		this.other = other;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DailyStatus.refRule
	 * @return  the value of DailyStatus.refRule
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public Integer getRefRule() {
		return refRule;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DailyStatus.refRule
	 * @param refRule  the value for DailyStatus.refRule
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public void setRefRule(Integer refRule) {
		this.refRule = refRule;
	}
}