package cn.scau.pojo;

import java.util.Date;

public class DailyStatusKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DailyStatus.ddate
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	private Date ddate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DailyStatus.rmType
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	private String rmType;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DailyStatus.ddate
	 * @return  the value of DailyStatus.ddate
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public Date getDdate() {
		return ddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DailyStatus.ddate
	 * @param ddate  the value for DailyStatus.ddate
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public void setDdate(Date ddate) {
		this.ddate = ddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DailyStatus.rmType
	 * @return  the value of DailyStatus.rmType
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public String getRmType() {
		return rmType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DailyStatus.rmType
	 * @param rmType  the value for DailyStatus.rmType
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public void setRmType(String rmType) {
		this.rmType = rmType;
	}
}