package cn.scau.pojo;

import java.sql.Date;

public class DailyRateKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DailyRate.ddate
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	private Date ddate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DailyRate.rmType
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	private String rmType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DailyRate.rateType
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	private String rateType;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DailyRate.ddate
	 * @return  the value of DailyRate.ddate
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public Date getDdate() {
		return ddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DailyRate.ddate
	 * @param ddate  the value for DailyRate.ddate
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public void setDdate(Date ddate) {
		this.ddate = ddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DailyRate.rmType
	 * @return  the value of DailyRate.rmType
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public String getRmType() {
		return rmType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DailyRate.rmType
	 * @param rmType  the value for DailyRate.rmType
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public void setRmType(String rmType) {
		this.rmType = rmType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DailyRate.rateType
	 * @return  the value of DailyRate.rateType
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public String getRateType() {
		return rateType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DailyRate.rateType
	 * @param rateType  the value for DailyRate.rateType
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public void setRateType(String rateType) {
		this.rateType = rateType;
	}
}