package cn.scau.pojo;

public class DailyRate extends DailyRateKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DailyRate.refRule
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	private Integer refRule;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DailyRate.rate
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	private Double rate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DailyRate.refRule
	 * @return  the value of DailyRate.refRule
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public Integer getRefRule() {
		return refRule;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DailyRate.refRule
	 * @param refRule  the value for DailyRate.refRule
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public void setRefRule(Integer refRule) {
		this.refRule = refRule;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DailyRate.rate
	 * @return  the value of DailyRate.rate
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public Double getRate() {
		return rate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DailyRate.rate
	 * @param rate  the value for DailyRate.rate
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public void setRate(Double rate) {
		this.rate = rate;
	}
}