package cn.scau.pojo;

import java.sql.Date;

public class DRS {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drs.ddate
     *
     * @mbg.generated Tue Aug 07 09:44:00 CST 2018
     */
    private Date ddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drs.rmType
     *
     * @mbg.generated Tue Aug 07 09:44:00 CST 2018
     */
    private String rmType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drs.rateType
     *
     * @mbg.generated Tue Aug 07 09:44:00 CST 2018
     */
    private String rateType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drs.rate
     *
     * @mbg.generated Tue Aug 07 09:44:00 CST 2018
     */
    private Double rate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drs.refRule
     *
     * @mbg.generated Tue Aug 07 09:44:00 CST 2018
     */
    private Integer refRule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drs.prepaid
     *
     * @mbg.generated Tue Aug 07 09:44:00 CST 2018
     */
    private Boolean prepaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drs.freeCancelDate
     *
     * @mbg.generated Tue Aug 07 09:44:00 CST 2018
     */
    private Integer freeCancelDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drs.isToAll
     *
     * @mbg.generated Tue Aug 07 09:44:00 CST 2018
     */
    private Boolean isToAll;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drs.num
     *
     * @mbg.generated Tue Aug 07 09:44:00 CST 2018
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drs.bed
     *
     * @mbg.generated Tue Aug 07 09:44:00 CST 2018
     */
    private Integer bed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drs.sold
     *
     * @mbg.generated Tue Aug 07 09:44:00 CST 2018
     */
    private Integer sold;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drs.other
     *
     * @mbg.generated Tue Aug 07 09:44:00 CST 2018
     */
    private Integer other;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drs.tier
     *
     * @mbg.generated Tue Aug 07 09:44:00 CST 2018
     */
    private Integer tier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drs.rest
     *
     * @mbg.generated Tue Aug 07 09:44:00 CST 2018
     */
    private Integer rest;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drs.ddate
     *
     * @return the value of drs.ddate
     *
     * @mbg.generated Tue Aug 07 09:44:00 CST 2018
     */
    public Date getDdate() {
        return ddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drs.ddate
     *
     * @param ddate the value for drs.ddate
     *
     * @mbg.generated Tue Aug 07 09:44:00 CST 2018
     */
    public void setDdate(Date ddate) {
        this.ddate = ddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drs.rmType
     *
     * @return the value of drs.rmType
     *
     * @mbg.generated Tue Aug 07 09:44:00 CST 2018
     */
    public String getRmType() {
        return rmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drs.rmType
     *
     * @param rmType the value for drs.rmType
     *
     * @mbg.generated Tue Aug 07 09:44:00 CST 2018
     */
    public void setRmType(String rmType) {
        this.rmType = rmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drs.rateType
     *
     * @return the value of drs.rateType
     *
     * @mbg.generated Tue Aug 07 09:44:00 CST 2018
     */
    public String getRateType() {
        return rateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drs.rateType
     *
     * @param rateType the value for drs.rateType
     *
     * @mbg.generated Tue Aug 07 09:44:00 CST 2018
     */
    public void setRateType(String rateType) {
        this.rateType = rateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drs.rate
     *
     * @return the value of drs.rate
     *
     * @mbg.generated Tue Aug 07 09:44:00 CST 2018
     */
    public Double getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drs.rate
     *
     * @param rate the value for drs.rate
     *
     * @mbg.generated Tue Aug 07 09:44:00 CST 2018
     */
    public void setRate(Double rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drs.refRule
     *
     * @return the value of drs.refRule
     *
     * @mbg.generated Tue Aug 07 09:44:00 CST 2018
     */
    public Integer getRefRule() {
        return refRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drs.refRule
     *
     * @param refRule the value for drs.refRule
     *
     * @mbg.generated Tue Aug 07 09:44:00 CST 2018
     */
    public void setRefRule(Integer refRule) {
        this.refRule = refRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drs.prepaid
     *
     * @return the value of drs.prepaid
     *
     * @mbg.generated Tue Aug 07 09:44:00 CST 2018
     */
    public Boolean getPrepaid() {
        return prepaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drs.prepaid
     *
     * @param prepaid the value for drs.prepaid
     *
     * @mbg.generated Tue Aug 07 09:44:00 CST 2018
     */
    public void setPrepaid(Boolean prepaid) {
        this.prepaid = prepaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drs.freeCancelDate
     *
     * @return the value of drs.freeCancelDate
     *
     * @mbg.generated Tue Aug 07 09:44:00 CST 2018
     */
    public Integer getFreeCancelDate() {
        return freeCancelDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drs.freeCancelDate
     *
     * @param freeCancelDate the value for drs.freeCancelDate
     *
     * @mbg.generated Tue Aug 07 09:44:00 CST 2018
     */
    public void setFreeCancelDate(Integer freeCancelDate) {
        this.freeCancelDate = freeCancelDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drs.isToAll
     *
     * @return the value of drs.isToAll
     *
     * @mbg.generated Tue Aug 07 09:44:00 CST 2018
     */
    public Boolean getIsToAll() {
        return isToAll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drs.isToAll
     *
     * @param isToAll the value for drs.isToAll
     *
     * @mbg.generated Tue Aug 07 09:44:00 CST 2018
     */
    public void setIsToAll(Boolean isToAll) {
        this.isToAll = isToAll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drs.num
     *
     * @return the value of drs.num
     *
     * @mbg.generated Tue Aug 07 09:44:00 CST 2018
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drs.num
     *
     * @param num the value for drs.num
     *
     * @mbg.generated Tue Aug 07 09:44:00 CST 2018
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drs.bed
     *
     * @return the value of drs.bed
     *
     * @mbg.generated Tue Aug 07 09:44:00 CST 2018
     */
    public Integer getBed() {
        return bed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drs.bed
     *
     * @param bed the value for drs.bed
     *
     * @mbg.generated Tue Aug 07 09:44:00 CST 2018
     */
    public void setBed(Integer bed) {
        this.bed = bed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drs.sold
     *
     * @return the value of drs.sold
     *
     * @mbg.generated Tue Aug 07 09:44:00 CST 2018
     */
    public Integer getSold() {
        return sold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drs.sold
     *
     * @param sold the value for drs.sold
     *
     * @mbg.generated Tue Aug 07 09:44:00 CST 2018
     */
    public void setSold(Integer sold) {
        this.sold = sold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drs.other
     *
     * @return the value of drs.other
     *
     * @mbg.generated Tue Aug 07 09:44:00 CST 2018
     */
    public Integer getOther() {
        return other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drs.other
     *
     * @param other the value for drs.other
     *
     * @mbg.generated Tue Aug 07 09:44:00 CST 2018
     */
    public void setOther(Integer other) {
        this.other = other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drs.tier
     *
     * @return the value of drs.tier
     *
     * @mbg.generated Tue Aug 07 09:44:00 CST 2018
     */
    public Integer getTier() {
        return tier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drs.tier
     *
     * @param tier the value for drs.tier
     *
     * @mbg.generated Tue Aug 07 09:44:00 CST 2018
     */
    public void setTier(Integer tier) {
        this.tier = tier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drs.rest
     *
     * @return the value of drs.rest
     *
     * @mbg.generated Tue Aug 07 09:44:00 CST 2018
     */
    public Integer getRest() {
        return rest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drs.rest
     *
     * @param rest the value for drs.rest
     *
     * @mbg.generated Tue Aug 07 09:44:00 CST 2018
     */
    public void setRest(Integer rest) {
        this.rest = rest;
    }
}