package cn.scau.pojo;

import java.sql.Date;

public class DS {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds.ddate
     *
     * @mbg.generated Wed Aug 08 13:23:44 CST 2018
     */
    private Date ddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds.rmType
     *
     * @mbg.generated Wed Aug 08 13:23:44 CST 2018
     */
    private String rmType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds.sold
     *
     * @mbg.generated Wed Aug 08 13:23:44 CST 2018
     */
    private Integer sold;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds.other
     *
     * @mbg.generated Wed Aug 08 13:23:44 CST 2018
     */
    private Integer other;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds.num
     *
     * @mbg.generated Wed Aug 08 13:23:44 CST 2018
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ds.rest
     *
     * @mbg.generated Wed Aug 08 13:23:44 CST 2018
     */
    private Long rest;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds.ddate
     *
     * @return the value of ds.ddate
     *
     * @mbg.generated Wed Aug 08 13:23:44 CST 2018
     */
    public Date getDdate() {
        return ddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds.ddate
     *
     * @param ddate the value for ds.ddate
     *
     * @mbg.generated Wed Aug 08 13:23:44 CST 2018
     */
    public void setDdate(Date ddate) {
        this.ddate = ddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds.rmType
     *
     * @return the value of ds.rmType
     *
     * @mbg.generated Wed Aug 08 13:23:44 CST 2018
     */
    public String getRmType() {
        return rmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds.rmType
     *
     * @param rmType the value for ds.rmType
     *
     * @mbg.generated Wed Aug 08 13:23:44 CST 2018
     */
    public void setRmType(String rmType) {
        this.rmType = rmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds.sold
     *
     * @return the value of ds.sold
     *
     * @mbg.generated Wed Aug 08 13:23:44 CST 2018
     */
    public Integer getSold() {
        return sold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds.sold
     *
     * @param sold the value for ds.sold
     *
     * @mbg.generated Wed Aug 08 13:23:44 CST 2018
     */
    public void setSold(Integer sold) {
        this.sold = sold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds.other
     *
     * @return the value of ds.other
     *
     * @mbg.generated Wed Aug 08 13:23:44 CST 2018
     */
    public Integer getOther() {
        return other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds.other
     *
     * @param other the value for ds.other
     *
     * @mbg.generated Wed Aug 08 13:23:44 CST 2018
     */
    public void setOther(Integer other) {
        this.other = other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds.num
     *
     * @return the value of ds.num
     *
     * @mbg.generated Wed Aug 08 13:23:44 CST 2018
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds.num
     *
     * @param num the value for ds.num
     *
     * @mbg.generated Wed Aug 08 13:23:44 CST 2018
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ds.rest
     *
     * @return the value of ds.rest
     *
     * @mbg.generated Wed Aug 08 13:23:44 CST 2018
     */
    public Long getRest() {
        return rest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ds.rest
     *
     * @param rest the value for ds.rest
     *
     * @mbg.generated Wed Aug 08 13:23:44 CST 2018
     */
    public void setRest(Long rest) {
        this.rest = rest;
    }
}