package cn.scau.pojo;

public class RateType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RateType.code
     *
     * @mbg.generated Sat Aug 04 20:04:16 CST 2018
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RateType.name
     *
     * @mbg.generated Sat Aug 04 20:04:16 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RateType.prepaid
     *
     * @mbg.generated Sat Aug 04 20:04:16 CST 2018
     */
    private Boolean prepaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RateType.freeCancelDate
     *
     * @mbg.generated Sat Aug 04 20:04:16 CST 2018
     */
    private Integer freeCancelDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RateType.isToAll
     *
     * @mbg.generated Sat Aug 04 20:04:16 CST 2018
     */
    private Boolean isToAll;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RateType.description
     *
     * @mbg.generated Sat Aug 04 20:04:16 CST 2018
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RateType.code
     *
     * @return the value of RateType.code
     *
     * @mbg.generated Sat Aug 04 20:04:16 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RateType.code
     *
     * @param code the value for RateType.code
     *
     * @mbg.generated Sat Aug 04 20:04:16 CST 2018
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RateType.name
     *
     * @return the value of RateType.name
     *
     * @mbg.generated Sat Aug 04 20:04:16 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RateType.name
     *
     * @param name the value for RateType.name
     *
     * @mbg.generated Sat Aug 04 20:04:16 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RateType.prepaid
     *
     * @return the value of RateType.prepaid
     *
     * @mbg.generated Sat Aug 04 20:04:16 CST 2018
     */
    public Boolean getPrepaid() {
        return prepaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RateType.prepaid
     *
     * @param prepaid the value for RateType.prepaid
     *
     * @mbg.generated Sat Aug 04 20:04:16 CST 2018
     */
    public void setPrepaid(Boolean prepaid) {
        this.prepaid = prepaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RateType.freeCancelDate
     *
     * @return the value of RateType.freeCancelDate
     *
     * @mbg.generated Sat Aug 04 20:04:16 CST 2018
     */
    public Integer getFreeCancelDate() {
        return freeCancelDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RateType.freeCancelDate
     *
     * @param freeCancelDate the value for RateType.freeCancelDate
     *
     * @mbg.generated Sat Aug 04 20:04:16 CST 2018
     */
    public void setFreeCancelDate(Integer freeCancelDate) {
        this.freeCancelDate = freeCancelDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RateType.isToAll
     *
     * @return the value of RateType.isToAll
     *
     * @mbg.generated Sat Aug 04 20:04:16 CST 2018
     */
    public Boolean getIsToAll() {
        return isToAll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RateType.isToAll
     *
     * @param isToAll the value for RateType.isToAll
     *
     * @mbg.generated Sat Aug 04 20:04:16 CST 2018
     */
    public void setIsToAll(Boolean isToAll) {
        this.isToAll = isToAll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RateType.description
     *
     * @return the value of RateType.description
     *
     * @mbg.generated Sat Aug 04 20:04:16 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RateType.description
     *
     * @param description the value for RateType.description
     *
     * @mbg.generated Sat Aug 04 20:04:16 CST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }
}