package cn.scau.pojo;

import java.sql.Date;

public class RateRule {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RateRule.id
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RateRule.fromDate
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	private Date fromDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RateRule.toDate
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	private Date toDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RateRule.rateType
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	private String rateType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RateRule.rmType
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	private String rmType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RateRule.mon
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	private Boolean mon;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RateRule.tue
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	private Boolean tue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RateRule.wed
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	private Boolean wed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RateRule.thu
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	private Boolean thu;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RateRule.fri
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	private Boolean fri;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RateRule.sat
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	private Boolean sat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RateRule.sun
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	private Boolean sun;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RateRule.rate
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	private Double rate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RateRule.notes
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	private String notes;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RateRule.id
	 * @return  the value of RateRule.id
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RateRule.id
	 * @param id  the value for RateRule.id
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RateRule.fromDate
	 * @return  the value of RateRule.fromDate
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public Date getFromDate() {
		return fromDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RateRule.fromDate
	 * @param fromDate  the value for RateRule.fromDate
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RateRule.toDate
	 * @return  the value of RateRule.toDate
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public Date getToDate() {
		return toDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RateRule.toDate
	 * @param toDate  the value for RateRule.toDate
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RateRule.rateType
	 * @return  the value of RateRule.rateType
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public String getRateType() {
		return rateType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RateRule.rateType
	 * @param rateType  the value for RateRule.rateType
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public void setRateType(String rateType) {
		this.rateType = rateType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RateRule.rmType
	 * @return  the value of RateRule.rmType
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public String getRmType() {
		return rmType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RateRule.rmType
	 * @param rmType  the value for RateRule.rmType
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public void setRmType(String rmType) {
		this.rmType = rmType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RateRule.mon
	 * @return  the value of RateRule.mon
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public Boolean getMon() {
		return mon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RateRule.mon
	 * @param mon  the value for RateRule.mon
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public void setMon(Boolean mon) {
		this.mon = mon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RateRule.tue
	 * @return  the value of RateRule.tue
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public Boolean getTue() {
		return tue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RateRule.tue
	 * @param tue  the value for RateRule.tue
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public void setTue(Boolean tue) {
		this.tue = tue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RateRule.wed
	 * @return  the value of RateRule.wed
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public Boolean getWed() {
		return wed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RateRule.wed
	 * @param wed  the value for RateRule.wed
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public void setWed(Boolean wed) {
		this.wed = wed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RateRule.thu
	 * @return  the value of RateRule.thu
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public Boolean getThu() {
		return thu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RateRule.thu
	 * @param thu  the value for RateRule.thu
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public void setThu(Boolean thu) {
		this.thu = thu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RateRule.fri
	 * @return  the value of RateRule.fri
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public Boolean getFri() {
		return fri;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RateRule.fri
	 * @param fri  the value for RateRule.fri
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public void setFri(Boolean fri) {
		this.fri = fri;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RateRule.sat
	 * @return  the value of RateRule.sat
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public Boolean getSat() {
		return sat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RateRule.sat
	 * @param sat  the value for RateRule.sat
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public void setSat(Boolean sat) {
		this.sat = sat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RateRule.sun
	 * @return  the value of RateRule.sun
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public Boolean getSun() {
		return sun;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RateRule.sun
	 * @param sun  the value for RateRule.sun
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public void setSun(Boolean sun) {
		this.sun = sun;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RateRule.rate
	 * @return  the value of RateRule.rate
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public Double getRate() {
		return rate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RateRule.rate
	 * @param rate  the value for RateRule.rate
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public void setRate(Double rate) {
		this.rate = rate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RateRule.notes
	 * @return  the value of RateRule.notes
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public String getNotes() {
		return notes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RateRule.notes
	 * @param notes  the value for RateRule.notes
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public void setNotes(String notes) {
		this.notes = notes;
	}
}