package cn.scau.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ReservationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Reservation
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Reservation
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Reservation
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Reservation
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public ReservationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Reservation
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Reservation
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Reservation
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Reservation
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Reservation
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Reservation
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Reservation
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Reservation
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Reservation
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Reservation
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Reservation
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andConfirmIDIsNull() {
            addCriterion("confirmID is null");
            return (Criteria) this;
        }

        public Criteria andConfirmIDIsNotNull() {
            addCriterion("confirmID is not null");
            return (Criteria) this;
        }

        public Criteria andConfirmIDEqualTo(Integer value) {
            addCriterion("confirmID =", value, "confirmID");
            return (Criteria) this;
        }

        public Criteria andConfirmIDNotEqualTo(Integer value) {
            addCriterion("confirmID <>", value, "confirmID");
            return (Criteria) this;
        }

        public Criteria andConfirmIDGreaterThan(Integer value) {
            addCriterion("confirmID >", value, "confirmID");
            return (Criteria) this;
        }

        public Criteria andConfirmIDGreaterThanOrEqualTo(Integer value) {
            addCriterion("confirmID >=", value, "confirmID");
            return (Criteria) this;
        }

        public Criteria andConfirmIDLessThan(Integer value) {
            addCriterion("confirmID <", value, "confirmID");
            return (Criteria) this;
        }

        public Criteria andConfirmIDLessThanOrEqualTo(Integer value) {
            addCriterion("confirmID <=", value, "confirmID");
            return (Criteria) this;
        }

        public Criteria andConfirmIDIn(List<Integer> values) {
            addCriterion("confirmID in", values, "confirmID");
            return (Criteria) this;
        }

        public Criteria andConfirmIDNotIn(List<Integer> values) {
            addCriterion("confirmID not in", values, "confirmID");
            return (Criteria) this;
        }

        public Criteria andConfirmIDBetween(Integer value1, Integer value2) {
            addCriterion("confirmID between", value1, value2, "confirmID");
            return (Criteria) this;
        }

        public Criteria andConfirmIDNotBetween(Integer value1, Integer value2) {
            addCriterion("confirmID not between", value1, value2, "confirmID");
            return (Criteria) this;
        }

        public Criteria andCiDateIsNull() {
            addCriterion("ciDate is null");
            return (Criteria) this;
        }

        public Criteria andCiDateIsNotNull() {
            addCriterion("ciDate is not null");
            return (Criteria) this;
        }

        public Criteria andCiDateEqualTo(Date value) {
            addCriterionForJDBCDate("ciDate =", value, "ciDate");
            return (Criteria) this;
        }

        public Criteria andCiDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("ciDate <>", value, "ciDate");
            return (Criteria) this;
        }

        public Criteria andCiDateGreaterThan(Date value) {
            addCriterionForJDBCDate("ciDate >", value, "ciDate");
            return (Criteria) this;
        }

        public Criteria andCiDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ciDate >=", value, "ciDate");
            return (Criteria) this;
        }

        public Criteria andCiDateLessThan(Date value) {
            addCriterionForJDBCDate("ciDate <", value, "ciDate");
            return (Criteria) this;
        }

        public Criteria andCiDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ciDate <=", value, "ciDate");
            return (Criteria) this;
        }

        public Criteria andCiDateIn(List<Date> values) {
            addCriterionForJDBCDate("ciDate in", values, "ciDate");
            return (Criteria) this;
        }

        public Criteria andCiDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("ciDate not in", values, "ciDate");
            return (Criteria) this;
        }

        public Criteria andCiDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ciDate between", value1, value2, "ciDate");
            return (Criteria) this;
        }

        public Criteria andCiDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ciDate not between", value1, value2, "ciDate");
            return (Criteria) this;
        }

        public Criteria andCoDateIsNull() {
            addCriterion("coDate is null");
            return (Criteria) this;
        }

        public Criteria andCoDateIsNotNull() {
            addCriterion("coDate is not null");
            return (Criteria) this;
        }

        public Criteria andCoDateEqualTo(Date value) {
            addCriterionForJDBCDate("coDate =", value, "coDate");
            return (Criteria) this;
        }

        public Criteria andCoDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("coDate <>", value, "coDate");
            return (Criteria) this;
        }

        public Criteria andCoDateGreaterThan(Date value) {
            addCriterionForJDBCDate("coDate >", value, "coDate");
            return (Criteria) this;
        }

        public Criteria andCoDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("coDate >=", value, "coDate");
            return (Criteria) this;
        }

        public Criteria andCoDateLessThan(Date value) {
            addCriterionForJDBCDate("coDate <", value, "coDate");
            return (Criteria) this;
        }

        public Criteria andCoDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("coDate <=", value, "coDate");
            return (Criteria) this;
        }

        public Criteria andCoDateIn(List<Date> values) {
            addCriterionForJDBCDate("coDate in", values, "coDate");
            return (Criteria) this;
        }

        public Criteria andCoDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("coDate not in", values, "coDate");
            return (Criteria) this;
        }

        public Criteria andCoDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("coDate between", value1, value2, "coDate");
            return (Criteria) this;
        }

        public Criteria andCoDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("coDate not between", value1, value2, "coDate");
            return (Criteria) this;
        }

        public Criteria andAdultsIsNull() {
            addCriterion("adults is null");
            return (Criteria) this;
        }

        public Criteria andAdultsIsNotNull() {
            addCriterion("adults is not null");
            return (Criteria) this;
        }

        public Criteria andAdultsEqualTo(Integer value) {
            addCriterion("adults =", value, "adults");
            return (Criteria) this;
        }

        public Criteria andAdultsNotEqualTo(Integer value) {
            addCriterion("adults <>", value, "adults");
            return (Criteria) this;
        }

        public Criteria andAdultsGreaterThan(Integer value) {
            addCriterion("adults >", value, "adults");
            return (Criteria) this;
        }

        public Criteria andAdultsGreaterThanOrEqualTo(Integer value) {
            addCriterion("adults >=", value, "adults");
            return (Criteria) this;
        }

        public Criteria andAdultsLessThan(Integer value) {
            addCriterion("adults <", value, "adults");
            return (Criteria) this;
        }

        public Criteria andAdultsLessThanOrEqualTo(Integer value) {
            addCriterion("adults <=", value, "adults");
            return (Criteria) this;
        }

        public Criteria andAdultsIn(List<Integer> values) {
            addCriterion("adults in", values, "adults");
            return (Criteria) this;
        }

        public Criteria andAdultsNotIn(List<Integer> values) {
            addCriterion("adults not in", values, "adults");
            return (Criteria) this;
        }

        public Criteria andAdultsBetween(Integer value1, Integer value2) {
            addCriterion("adults between", value1, value2, "adults");
            return (Criteria) this;
        }

        public Criteria andAdultsNotBetween(Integer value1, Integer value2) {
            addCriterion("adults not between", value1, value2, "adults");
            return (Criteria) this;
        }

        public Criteria andChildIsNull() {
            addCriterion("child is null");
            return (Criteria) this;
        }

        public Criteria andChildIsNotNull() {
            addCriterion("child is not null");
            return (Criteria) this;
        }

        public Criteria andChildEqualTo(Integer value) {
            addCriterion("child =", value, "child");
            return (Criteria) this;
        }

        public Criteria andChildNotEqualTo(Integer value) {
            addCriterion("child <>", value, "child");
            return (Criteria) this;
        }

        public Criteria andChildGreaterThan(Integer value) {
            addCriterion("child >", value, "child");
            return (Criteria) this;
        }

        public Criteria andChildGreaterThanOrEqualTo(Integer value) {
            addCriterion("child >=", value, "child");
            return (Criteria) this;
        }

        public Criteria andChildLessThan(Integer value) {
            addCriterion("child <", value, "child");
            return (Criteria) this;
        }

        public Criteria andChildLessThanOrEqualTo(Integer value) {
            addCriterion("child <=", value, "child");
            return (Criteria) this;
        }

        public Criteria andChildIn(List<Integer> values) {
            addCriterion("child in", values, "child");
            return (Criteria) this;
        }

        public Criteria andChildNotIn(List<Integer> values) {
            addCriterion("child not in", values, "child");
            return (Criteria) this;
        }

        public Criteria andChildBetween(Integer value1, Integer value2) {
            addCriterion("child between", value1, value2, "child");
            return (Criteria) this;
        }

        public Criteria andChildNotBetween(Integer value1, Integer value2) {
            addCriterion("child not between", value1, value2, "child");
            return (Criteria) this;
        }

        public Criteria andQuantityIsNull() {
            addCriterion("quantity is null");
            return (Criteria) this;
        }

        public Criteria andQuantityIsNotNull() {
            addCriterion("quantity is not null");
            return (Criteria) this;
        }

        public Criteria andQuantityEqualTo(Integer value) {
            addCriterion("quantity =", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityNotEqualTo(Integer value) {
            addCriterion("quantity <>", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityGreaterThan(Integer value) {
            addCriterion("quantity >", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityGreaterThanOrEqualTo(Integer value) {
            addCriterion("quantity >=", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityLessThan(Integer value) {
            addCriterion("quantity <", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityLessThanOrEqualTo(Integer value) {
            addCriterion("quantity <=", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityIn(List<Integer> values) {
            addCriterion("quantity in", values, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityNotIn(List<Integer> values) {
            addCriterion("quantity not in", values, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityBetween(Integer value1, Integer value2) {
            addCriterion("quantity between", value1, value2, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityNotBetween(Integer value1, Integer value2) {
            addCriterion("quantity not between", value1, value2, "quantity");
            return (Criteria) this;
        }

        public Criteria andRmTypeIsNull() {
            addCriterion("rmType is null");
            return (Criteria) this;
        }

        public Criteria andRmTypeIsNotNull() {
            addCriterion("rmType is not null");
            return (Criteria) this;
        }

        public Criteria andRmTypeEqualTo(String value) {
            addCriterion("rmType =", value, "rmType");
            return (Criteria) this;
        }

        public Criteria andRmTypeNotEqualTo(String value) {
            addCriterion("rmType <>", value, "rmType");
            return (Criteria) this;
        }

        public Criteria andRmTypeGreaterThan(String value) {
            addCriterion("rmType >", value, "rmType");
            return (Criteria) this;
        }

        public Criteria andRmTypeGreaterThanOrEqualTo(String value) {
            addCriterion("rmType >=", value, "rmType");
            return (Criteria) this;
        }

        public Criteria andRmTypeLessThan(String value) {
            addCriterion("rmType <", value, "rmType");
            return (Criteria) this;
        }

        public Criteria andRmTypeLessThanOrEqualTo(String value) {
            addCriterion("rmType <=", value, "rmType");
            return (Criteria) this;
        }

        public Criteria andRmTypeLike(String value) {
            addCriterion("rmType like", value, "rmType");
            return (Criteria) this;
        }

        public Criteria andRmTypeNotLike(String value) {
            addCriterion("rmType not like", value, "rmType");
            return (Criteria) this;
        }

        public Criteria andRmTypeIn(List<String> values) {
            addCriterion("rmType in", values, "rmType");
            return (Criteria) this;
        }

        public Criteria andRmTypeNotIn(List<String> values) {
            addCriterion("rmType not in", values, "rmType");
            return (Criteria) this;
        }

        public Criteria andRmTypeBetween(String value1, String value2) {
            addCriterion("rmType between", value1, value2, "rmType");
            return (Criteria) this;
        }

        public Criteria andRmTypeNotBetween(String value1, String value2) {
            addCriterion("rmType not between", value1, value2, "rmType");
            return (Criteria) this;
        }

        public Criteria andRateTypeIsNull() {
            addCriterion("rateType is null");
            return (Criteria) this;
        }

        public Criteria andRateTypeIsNotNull() {
            addCriterion("rateType is not null");
            return (Criteria) this;
        }

        public Criteria andRateTypeEqualTo(String value) {
            addCriterion("rateType =", value, "rateType");
            return (Criteria) this;
        }

        public Criteria andRateTypeNotEqualTo(String value) {
            addCriterion("rateType <>", value, "rateType");
            return (Criteria) this;
        }

        public Criteria andRateTypeGreaterThan(String value) {
            addCriterion("rateType >", value, "rateType");
            return (Criteria) this;
        }

        public Criteria andRateTypeGreaterThanOrEqualTo(String value) {
            addCriterion("rateType >=", value, "rateType");
            return (Criteria) this;
        }

        public Criteria andRateTypeLessThan(String value) {
            addCriterion("rateType <", value, "rateType");
            return (Criteria) this;
        }

        public Criteria andRateTypeLessThanOrEqualTo(String value) {
            addCriterion("rateType <=", value, "rateType");
            return (Criteria) this;
        }

        public Criteria andRateTypeLike(String value) {
            addCriterion("rateType like", value, "rateType");
            return (Criteria) this;
        }

        public Criteria andRateTypeNotLike(String value) {
            addCriterion("rateType not like", value, "rateType");
            return (Criteria) this;
        }

        public Criteria andRateTypeIn(List<String> values) {
            addCriterion("rateType in", values, "rateType");
            return (Criteria) this;
        }

        public Criteria andRateTypeNotIn(List<String> values) {
            addCriterion("rateType not in", values, "rateType");
            return (Criteria) this;
        }

        public Criteria andRateTypeBetween(String value1, String value2) {
            addCriterion("rateType between", value1, value2, "rateType");
            return (Criteria) this;
        }

        public Criteria andRateTypeNotBetween(String value1, String value2) {
            addCriterion("rateType not between", value1, value2, "rateType");
            return (Criteria) this;
        }

        public Criteria andAmountIsNull() {
            addCriterion("amount is null");
            return (Criteria) this;
        }

        public Criteria andAmountIsNotNull() {
            addCriterion("amount is not null");
            return (Criteria) this;
        }

        public Criteria andAmountEqualTo(Double value) {
            addCriterion("amount =", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotEqualTo(Double value) {
            addCriterion("amount <>", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThan(Double value) {
            addCriterion("amount >", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThanOrEqualTo(Double value) {
            addCriterion("amount >=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThan(Double value) {
            addCriterion("amount <", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThanOrEqualTo(Double value) {
            addCriterion("amount <=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountIn(List<Double> values) {
            addCriterion("amount in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotIn(List<Double> values) {
            addCriterion("amount not in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountBetween(Double value1, Double value2) {
            addCriterion("amount between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotBetween(Double value1, Double value2) {
            addCriterion("amount not between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andTitle1IsNull() {
            addCriterion("title1 is null");
            return (Criteria) this;
        }

        public Criteria andTitle1IsNotNull() {
            addCriterion("title1 is not null");
            return (Criteria) this;
        }

        public Criteria andTitle1EqualTo(String value) {
            addCriterion("title1 =", value, "title1");
            return (Criteria) this;
        }

        public Criteria andTitle1NotEqualTo(String value) {
            addCriterion("title1 <>", value, "title1");
            return (Criteria) this;
        }

        public Criteria andTitle1GreaterThan(String value) {
            addCriterion("title1 >", value, "title1");
            return (Criteria) this;
        }

        public Criteria andTitle1GreaterThanOrEqualTo(String value) {
            addCriterion("title1 >=", value, "title1");
            return (Criteria) this;
        }

        public Criteria andTitle1LessThan(String value) {
            addCriterion("title1 <", value, "title1");
            return (Criteria) this;
        }

        public Criteria andTitle1LessThanOrEqualTo(String value) {
            addCriterion("title1 <=", value, "title1");
            return (Criteria) this;
        }

        public Criteria andTitle1Like(String value) {
            addCriterion("title1 like", value, "title1");
            return (Criteria) this;
        }

        public Criteria andTitle1NotLike(String value) {
            addCriterion("title1 not like", value, "title1");
            return (Criteria) this;
        }

        public Criteria andTitle1In(List<String> values) {
            addCriterion("title1 in", values, "title1");
            return (Criteria) this;
        }

        public Criteria andTitle1NotIn(List<String> values) {
            addCriterion("title1 not in", values, "title1");
            return (Criteria) this;
        }

        public Criteria andTitle1Between(String value1, String value2) {
            addCriterion("title1 between", value1, value2, "title1");
            return (Criteria) this;
        }

        public Criteria andTitle1NotBetween(String value1, String value2) {
            addCriterion("title1 not between", value1, value2, "title1");
            return (Criteria) this;
        }

        public Criteria andName1IsNull() {
            addCriterion("name1 is null");
            return (Criteria) this;
        }

        public Criteria andName1IsNotNull() {
            addCriterion("name1 is not null");
            return (Criteria) this;
        }

        public Criteria andName1EqualTo(String value) {
            addCriterion("name1 =", value, "name1");
            return (Criteria) this;
        }

        public Criteria andName1NotEqualTo(String value) {
            addCriterion("name1 <>", value, "name1");
            return (Criteria) this;
        }

        public Criteria andName1GreaterThan(String value) {
            addCriterion("name1 >", value, "name1");
            return (Criteria) this;
        }

        public Criteria andName1GreaterThanOrEqualTo(String value) {
            addCriterion("name1 >=", value, "name1");
            return (Criteria) this;
        }

        public Criteria andName1LessThan(String value) {
            addCriterion("name1 <", value, "name1");
            return (Criteria) this;
        }

        public Criteria andName1LessThanOrEqualTo(String value) {
            addCriterion("name1 <=", value, "name1");
            return (Criteria) this;
        }

        public Criteria andName1Like(String value) {
            addCriterion("name1 like", value, "name1");
            return (Criteria) this;
        }

        public Criteria andName1NotLike(String value) {
            addCriterion("name1 not like", value, "name1");
            return (Criteria) this;
        }

        public Criteria andName1In(List<String> values) {
            addCriterion("name1 in", values, "name1");
            return (Criteria) this;
        }

        public Criteria andName1NotIn(List<String> values) {
            addCriterion("name1 not in", values, "name1");
            return (Criteria) this;
        }

        public Criteria andName1Between(String value1, String value2) {
            addCriterion("name1 between", value1, value2, "name1");
            return (Criteria) this;
        }

        public Criteria andName1NotBetween(String value1, String value2) {
            addCriterion("name1 not between", value1, value2, "name1");
            return (Criteria) this;
        }

        public Criteria andSurname1IsNull() {
            addCriterion("surname1 is null");
            return (Criteria) this;
        }

        public Criteria andSurname1IsNotNull() {
            addCriterion("surname1 is not null");
            return (Criteria) this;
        }

        public Criteria andSurname1EqualTo(String value) {
            addCriterion("surname1 =", value, "surname1");
            return (Criteria) this;
        }

        public Criteria andSurname1NotEqualTo(String value) {
            addCriterion("surname1 <>", value, "surname1");
            return (Criteria) this;
        }

        public Criteria andSurname1GreaterThan(String value) {
            addCriterion("surname1 >", value, "surname1");
            return (Criteria) this;
        }

        public Criteria andSurname1GreaterThanOrEqualTo(String value) {
            addCriterion("surname1 >=", value, "surname1");
            return (Criteria) this;
        }

        public Criteria andSurname1LessThan(String value) {
            addCriterion("surname1 <", value, "surname1");
            return (Criteria) this;
        }

        public Criteria andSurname1LessThanOrEqualTo(String value) {
            addCriterion("surname1 <=", value, "surname1");
            return (Criteria) this;
        }

        public Criteria andSurname1Like(String value) {
            addCriterion("surname1 like", value, "surname1");
            return (Criteria) this;
        }

        public Criteria andSurname1NotLike(String value) {
            addCriterion("surname1 not like", value, "surname1");
            return (Criteria) this;
        }

        public Criteria andSurname1In(List<String> values) {
            addCriterion("surname1 in", values, "surname1");
            return (Criteria) this;
        }

        public Criteria andSurname1NotIn(List<String> values) {
            addCriterion("surname1 not in", values, "surname1");
            return (Criteria) this;
        }

        public Criteria andSurname1Between(String value1, String value2) {
            addCriterion("surname1 between", value1, value2, "surname1");
            return (Criteria) this;
        }

        public Criteria andSurname1NotBetween(String value1, String value2) {
            addCriterion("surname1 not between", value1, value2, "surname1");
            return (Criteria) this;
        }

        public Criteria andTitle12IsNull() {
            addCriterion("title12 is null");
            return (Criteria) this;
        }

        public Criteria andTitle12IsNotNull() {
            addCriterion("title12 is not null");
            return (Criteria) this;
        }

        public Criteria andTitle12EqualTo(String value) {
            addCriterion("title12 =", value, "title12");
            return (Criteria) this;
        }

        public Criteria andTitle12NotEqualTo(String value) {
            addCriterion("title12 <>", value, "title12");
            return (Criteria) this;
        }

        public Criteria andTitle12GreaterThan(String value) {
            addCriterion("title12 >", value, "title12");
            return (Criteria) this;
        }

        public Criteria andTitle12GreaterThanOrEqualTo(String value) {
            addCriterion("title12 >=", value, "title12");
            return (Criteria) this;
        }

        public Criteria andTitle12LessThan(String value) {
            addCriterion("title12 <", value, "title12");
            return (Criteria) this;
        }

        public Criteria andTitle12LessThanOrEqualTo(String value) {
            addCriterion("title12 <=", value, "title12");
            return (Criteria) this;
        }

        public Criteria andTitle12Like(String value) {
            addCriterion("title12 like", value, "title12");
            return (Criteria) this;
        }

        public Criteria andTitle12NotLike(String value) {
            addCriterion("title12 not like", value, "title12");
            return (Criteria) this;
        }

        public Criteria andTitle12In(List<String> values) {
            addCriterion("title12 in", values, "title12");
            return (Criteria) this;
        }

        public Criteria andTitle12NotIn(List<String> values) {
            addCriterion("title12 not in", values, "title12");
            return (Criteria) this;
        }

        public Criteria andTitle12Between(String value1, String value2) {
            addCriterion("title12 between", value1, value2, "title12");
            return (Criteria) this;
        }

        public Criteria andTitle12NotBetween(String value1, String value2) {
            addCriterion("title12 not between", value1, value2, "title12");
            return (Criteria) this;
        }

        public Criteria andName2IsNull() {
            addCriterion("name2 is null");
            return (Criteria) this;
        }

        public Criteria andName2IsNotNull() {
            addCriterion("name2 is not null");
            return (Criteria) this;
        }

        public Criteria andName2EqualTo(String value) {
            addCriterion("name2 =", value, "name2");
            return (Criteria) this;
        }

        public Criteria andName2NotEqualTo(String value) {
            addCriterion("name2 <>", value, "name2");
            return (Criteria) this;
        }

        public Criteria andName2GreaterThan(String value) {
            addCriterion("name2 >", value, "name2");
            return (Criteria) this;
        }

        public Criteria andName2GreaterThanOrEqualTo(String value) {
            addCriterion("name2 >=", value, "name2");
            return (Criteria) this;
        }

        public Criteria andName2LessThan(String value) {
            addCriterion("name2 <", value, "name2");
            return (Criteria) this;
        }

        public Criteria andName2LessThanOrEqualTo(String value) {
            addCriterion("name2 <=", value, "name2");
            return (Criteria) this;
        }

        public Criteria andName2Like(String value) {
            addCriterion("name2 like", value, "name2");
            return (Criteria) this;
        }

        public Criteria andName2NotLike(String value) {
            addCriterion("name2 not like", value, "name2");
            return (Criteria) this;
        }

        public Criteria andName2In(List<String> values) {
            addCriterion("name2 in", values, "name2");
            return (Criteria) this;
        }

        public Criteria andName2NotIn(List<String> values) {
            addCriterion("name2 not in", values, "name2");
            return (Criteria) this;
        }

        public Criteria andName2Between(String value1, String value2) {
            addCriterion("name2 between", value1, value2, "name2");
            return (Criteria) this;
        }

        public Criteria andName2NotBetween(String value1, String value2) {
            addCriterion("name2 not between", value1, value2, "name2");
            return (Criteria) this;
        }

        public Criteria andSurname2IsNull() {
            addCriterion("surname2 is null");
            return (Criteria) this;
        }

        public Criteria andSurname2IsNotNull() {
            addCriterion("surname2 is not null");
            return (Criteria) this;
        }

        public Criteria andSurname2EqualTo(String value) {
            addCriterion("surname2 =", value, "surname2");
            return (Criteria) this;
        }

        public Criteria andSurname2NotEqualTo(String value) {
            addCriterion("surname2 <>", value, "surname2");
            return (Criteria) this;
        }

        public Criteria andSurname2GreaterThan(String value) {
            addCriterion("surname2 >", value, "surname2");
            return (Criteria) this;
        }

        public Criteria andSurname2GreaterThanOrEqualTo(String value) {
            addCriterion("surname2 >=", value, "surname2");
            return (Criteria) this;
        }

        public Criteria andSurname2LessThan(String value) {
            addCriterion("surname2 <", value, "surname2");
            return (Criteria) this;
        }

        public Criteria andSurname2LessThanOrEqualTo(String value) {
            addCriterion("surname2 <=", value, "surname2");
            return (Criteria) this;
        }

        public Criteria andSurname2Like(String value) {
            addCriterion("surname2 like", value, "surname2");
            return (Criteria) this;
        }

        public Criteria andSurname2NotLike(String value) {
            addCriterion("surname2 not like", value, "surname2");
            return (Criteria) this;
        }

        public Criteria andSurname2In(List<String> values) {
            addCriterion("surname2 in", values, "surname2");
            return (Criteria) this;
        }

        public Criteria andSurname2NotIn(List<String> values) {
            addCriterion("surname2 not in", values, "surname2");
            return (Criteria) this;
        }

        public Criteria andSurname2Between(String value1, String value2) {
            addCriterion("surname2 between", value1, value2, "surname2");
            return (Criteria) this;
        }

        public Criteria andSurname2NotBetween(String value1, String value2) {
            addCriterion("surname2 not between", value1, value2, "surname2");
            return (Criteria) this;
        }

        public Criteria andCityIsNull() {
            addCriterion("city is null");
            return (Criteria) this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("city is not null");
            return (Criteria) this;
        }

        public Criteria andCityEqualTo(String value) {
            addCriterion("city =", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotEqualTo(String value) {
            addCriterion("city <>", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThan(String value) {
            addCriterion("city >", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThanOrEqualTo(String value) {
            addCriterion("city >=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThan(String value) {
            addCriterion("city <", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThanOrEqualTo(String value) {
            addCriterion("city <=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLike(String value) {
            addCriterion("city like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotLike(String value) {
            addCriterion("city not like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityIn(List<String> values) {
            addCriterion("city in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotIn(List<String> values) {
            addCriterion("city not in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityBetween(String value1, String value2) {
            addCriterion("city between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotBetween(String value1, String value2) {
            addCriterion("city not between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andZipIsNull() {
            addCriterion("zip is null");
            return (Criteria) this;
        }

        public Criteria andZipIsNotNull() {
            addCriterion("zip is not null");
            return (Criteria) this;
        }

        public Criteria andZipEqualTo(String value) {
            addCriterion("zip =", value, "zip");
            return (Criteria) this;
        }

        public Criteria andZipNotEqualTo(String value) {
            addCriterion("zip <>", value, "zip");
            return (Criteria) this;
        }

        public Criteria andZipGreaterThan(String value) {
            addCriterion("zip >", value, "zip");
            return (Criteria) this;
        }

        public Criteria andZipGreaterThanOrEqualTo(String value) {
            addCriterion("zip >=", value, "zip");
            return (Criteria) this;
        }

        public Criteria andZipLessThan(String value) {
            addCriterion("zip <", value, "zip");
            return (Criteria) this;
        }

        public Criteria andZipLessThanOrEqualTo(String value) {
            addCriterion("zip <=", value, "zip");
            return (Criteria) this;
        }

        public Criteria andZipLike(String value) {
            addCriterion("zip like", value, "zip");
            return (Criteria) this;
        }

        public Criteria andZipNotLike(String value) {
            addCriterion("zip not like", value, "zip");
            return (Criteria) this;
        }

        public Criteria andZipIn(List<String> values) {
            addCriterion("zip in", values, "zip");
            return (Criteria) this;
        }

        public Criteria andZipNotIn(List<String> values) {
            addCriterion("zip not in", values, "zip");
            return (Criteria) this;
        }

        public Criteria andZipBetween(String value1, String value2) {
            addCriterion("zip between", value1, value2, "zip");
            return (Criteria) this;
        }

        public Criteria andZipNotBetween(String value1, String value2) {
            addCriterion("zip not between", value1, value2, "zip");
            return (Criteria) this;
        }

        public Criteria andCountryIsNull() {
            addCriterion("country is null");
            return (Criteria) this;
        }

        public Criteria andCountryIsNotNull() {
            addCriterion("country is not null");
            return (Criteria) this;
        }

        public Criteria andCountryEqualTo(String value) {
            addCriterion("country =", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotEqualTo(String value) {
            addCriterion("country <>", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryGreaterThan(String value) {
            addCriterion("country >", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryGreaterThanOrEqualTo(String value) {
            addCriterion("country >=", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLessThan(String value) {
            addCriterion("country <", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLessThanOrEqualTo(String value) {
            addCriterion("country <=", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLike(String value) {
            addCriterion("country like", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotLike(String value) {
            addCriterion("country not like", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryIn(List<String> values) {
            addCriterion("country in", values, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotIn(List<String> values) {
            addCriterion("country not in", values, "country");
            return (Criteria) this;
        }

        public Criteria andCountryBetween(String value1, String value2) {
            addCriterion("country between", value1, value2, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotBetween(String value1, String value2) {
            addCriterion("country not between", value1, value2, "country");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("phone is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("phone is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("phone =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("phone <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("phone >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("phone >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("phone <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("phone <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("phone like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("phone not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("phone in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("phone not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("phone between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("phone not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andCardTypeIsNull() {
            addCriterion("cardType is null");
            return (Criteria) this;
        }

        public Criteria andCardTypeIsNotNull() {
            addCriterion("cardType is not null");
            return (Criteria) this;
        }

        public Criteria andCardTypeEqualTo(String value) {
            addCriterion("cardType =", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeNotEqualTo(String value) {
            addCriterion("cardType <>", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeGreaterThan(String value) {
            addCriterion("cardType >", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeGreaterThanOrEqualTo(String value) {
            addCriterion("cardType >=", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeLessThan(String value) {
            addCriterion("cardType <", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeLessThanOrEqualTo(String value) {
            addCriterion("cardType <=", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeLike(String value) {
            addCriterion("cardType like", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeNotLike(String value) {
            addCriterion("cardType not like", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeIn(List<String> values) {
            addCriterion("cardType in", values, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeNotIn(List<String> values) {
            addCriterion("cardType not in", values, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeBetween(String value1, String value2) {
            addCriterion("cardType between", value1, value2, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeNotBetween(String value1, String value2) {
            addCriterion("cardType not between", value1, value2, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardNumberIsNull() {
            addCriterion("cardNumber is null");
            return (Criteria) this;
        }

        public Criteria andCardNumberIsNotNull() {
            addCriterion("cardNumber is not null");
            return (Criteria) this;
        }

        public Criteria andCardNumberEqualTo(String value) {
            addCriterion("cardNumber =", value, "cardNumber");
            return (Criteria) this;
        }

        public Criteria andCardNumberNotEqualTo(String value) {
            addCriterion("cardNumber <>", value, "cardNumber");
            return (Criteria) this;
        }

        public Criteria andCardNumberGreaterThan(String value) {
            addCriterion("cardNumber >", value, "cardNumber");
            return (Criteria) this;
        }

        public Criteria andCardNumberGreaterThanOrEqualTo(String value) {
            addCriterion("cardNumber >=", value, "cardNumber");
            return (Criteria) this;
        }

        public Criteria andCardNumberLessThan(String value) {
            addCriterion("cardNumber <", value, "cardNumber");
            return (Criteria) this;
        }

        public Criteria andCardNumberLessThanOrEqualTo(String value) {
            addCriterion("cardNumber <=", value, "cardNumber");
            return (Criteria) this;
        }

        public Criteria andCardNumberLike(String value) {
            addCriterion("cardNumber like", value, "cardNumber");
            return (Criteria) this;
        }

        public Criteria andCardNumberNotLike(String value) {
            addCriterion("cardNumber not like", value, "cardNumber");
            return (Criteria) this;
        }

        public Criteria andCardNumberIn(List<String> values) {
            addCriterion("cardNumber in", values, "cardNumber");
            return (Criteria) this;
        }

        public Criteria andCardNumberNotIn(List<String> values) {
            addCriterion("cardNumber not in", values, "cardNumber");
            return (Criteria) this;
        }

        public Criteria andCardNumberBetween(String value1, String value2) {
            addCriterion("cardNumber between", value1, value2, "cardNumber");
            return (Criteria) this;
        }

        public Criteria andCardNumberNotBetween(String value1, String value2) {
            addCriterion("cardNumber not between", value1, value2, "cardNumber");
            return (Criteria) this;
        }

        public Criteria andCardExpireIsNull() {
            addCriterion("cardExpire is null");
            return (Criteria) this;
        }

        public Criteria andCardExpireIsNotNull() {
            addCriterion("cardExpire is not null");
            return (Criteria) this;
        }

        public Criteria andCardExpireEqualTo(String value) {
            addCriterion("cardExpire =", value, "cardExpire");
            return (Criteria) this;
        }

        public Criteria andCardExpireNotEqualTo(String value) {
            addCriterion("cardExpire <>", value, "cardExpire");
            return (Criteria) this;
        }

        public Criteria andCardExpireGreaterThan(String value) {
            addCriterion("cardExpire >", value, "cardExpire");
            return (Criteria) this;
        }

        public Criteria andCardExpireGreaterThanOrEqualTo(String value) {
            addCriterion("cardExpire >=", value, "cardExpire");
            return (Criteria) this;
        }

        public Criteria andCardExpireLessThan(String value) {
            addCriterion("cardExpire <", value, "cardExpire");
            return (Criteria) this;
        }

        public Criteria andCardExpireLessThanOrEqualTo(String value) {
            addCriterion("cardExpire <=", value, "cardExpire");
            return (Criteria) this;
        }

        public Criteria andCardExpireLike(String value) {
            addCriterion("cardExpire like", value, "cardExpire");
            return (Criteria) this;
        }

        public Criteria andCardExpireNotLike(String value) {
            addCriterion("cardExpire not like", value, "cardExpire");
            return (Criteria) this;
        }

        public Criteria andCardExpireIn(List<String> values) {
            addCriterion("cardExpire in", values, "cardExpire");
            return (Criteria) this;
        }

        public Criteria andCardExpireNotIn(List<String> values) {
            addCriterion("cardExpire not in", values, "cardExpire");
            return (Criteria) this;
        }

        public Criteria andCardExpireBetween(String value1, String value2) {
            addCriterion("cardExpire between", value1, value2, "cardExpire");
            return (Criteria) this;
        }

        public Criteria andCardExpireNotBetween(String value1, String value2) {
            addCriterion("cardExpire not between", value1, value2, "cardExpire");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andFreeCancelDateIsNull() {
            addCriterion("freeCancelDate is null");
            return (Criteria) this;
        }

        public Criteria andFreeCancelDateIsNotNull() {
            addCriterion("freeCancelDate is not null");
            return (Criteria) this;
        }

        public Criteria andFreeCancelDateEqualTo(Date value) {
            addCriterion("freeCancelDate =", value, "freeCancelDate");
            return (Criteria) this;
        }

        public Criteria andFreeCancelDateNotEqualTo(Date value) {
            addCriterion("freeCancelDate <>", value, "freeCancelDate");
            return (Criteria) this;
        }

        public Criteria andFreeCancelDateGreaterThan(Date value) {
            addCriterion("freeCancelDate >", value, "freeCancelDate");
            return (Criteria) this;
        }

        public Criteria andFreeCancelDateGreaterThanOrEqualTo(Date value) {
            addCriterion("freeCancelDate >=", value, "freeCancelDate");
            return (Criteria) this;
        }

        public Criteria andFreeCancelDateLessThan(Date value) {
            addCriterion("freeCancelDate <", value, "freeCancelDate");
            return (Criteria) this;
        }

        public Criteria andFreeCancelDateLessThanOrEqualTo(Date value) {
            addCriterion("freeCancelDate <=", value, "freeCancelDate");
            return (Criteria) this;
        }

        public Criteria andFreeCancelDateIn(List<Date> values) {
            addCriterion("freeCancelDate in", values, "freeCancelDate");
            return (Criteria) this;
        }

        public Criteria andFreeCancelDateNotIn(List<Date> values) {
            addCriterion("freeCancelDate not in", values, "freeCancelDate");
            return (Criteria) this;
        }

        public Criteria andFreeCancelDateBetween(Date value1, Date value2) {
            addCriterion("freeCancelDate between", value1, value2, "freeCancelDate");
            return (Criteria) this;
        }

        public Criteria andFreeCancelDateNotBetween(Date value1, Date value2) {
            addCriterion("freeCancelDate not between", value1, value2, "freeCancelDate");
            return (Criteria) this;
        }

        public Criteria andRsvFromIsNull() {
            addCriterion("rsvFrom is null");
            return (Criteria) this;
        }

        public Criteria andRsvFromIsNotNull() {
            addCriterion("rsvFrom is not null");
            return (Criteria) this;
        }

        public Criteria andRsvFromEqualTo(String value) {
            addCriterion("rsvFrom =", value, "rsvFrom");
            return (Criteria) this;
        }

        public Criteria andRsvFromNotEqualTo(String value) {
            addCriterion("rsvFrom <>", value, "rsvFrom");
            return (Criteria) this;
        }

        public Criteria andRsvFromGreaterThan(String value) {
            addCriterion("rsvFrom >", value, "rsvFrom");
            return (Criteria) this;
        }

        public Criteria andRsvFromGreaterThanOrEqualTo(String value) {
            addCriterion("rsvFrom >=", value, "rsvFrom");
            return (Criteria) this;
        }

        public Criteria andRsvFromLessThan(String value) {
            addCriterion("rsvFrom <", value, "rsvFrom");
            return (Criteria) this;
        }

        public Criteria andRsvFromLessThanOrEqualTo(String value) {
            addCriterion("rsvFrom <=", value, "rsvFrom");
            return (Criteria) this;
        }

        public Criteria andRsvFromLike(String value) {
            addCriterion("rsvFrom like", value, "rsvFrom");
            return (Criteria) this;
        }

        public Criteria andRsvFromNotLike(String value) {
            addCriterion("rsvFrom not like", value, "rsvFrom");
            return (Criteria) this;
        }

        public Criteria andRsvFromIn(List<String> values) {
            addCriterion("rsvFrom in", values, "rsvFrom");
            return (Criteria) this;
        }

        public Criteria andRsvFromNotIn(List<String> values) {
            addCriterion("rsvFrom not in", values, "rsvFrom");
            return (Criteria) this;
        }

        public Criteria andRsvFromBetween(String value1, String value2) {
            addCriterion("rsvFrom between", value1, value2, "rsvFrom");
            return (Criteria) this;
        }

        public Criteria andRsvFromNotBetween(String value1, String value2) {
            addCriterion("rsvFrom not between", value1, value2, "rsvFrom");
            return (Criteria) this;
        }

        public Criteria andMadeDateIsNull() {
            addCriterion("madeDate is null");
            return (Criteria) this;
        }

        public Criteria andMadeDateIsNotNull() {
            addCriterion("madeDate is not null");
            return (Criteria) this;
        }

        public Criteria andMadeDateEqualTo(Date value) {
            addCriterion("madeDate =", value, "madeDate");
            return (Criteria) this;
        }

        public Criteria andMadeDateNotEqualTo(Date value) {
            addCriterion("madeDate <>", value, "madeDate");
            return (Criteria) this;
        }

        public Criteria andMadeDateGreaterThan(Date value) {
            addCriterion("madeDate >", value, "madeDate");
            return (Criteria) this;
        }

        public Criteria andMadeDateGreaterThanOrEqualTo(Date value) {
            addCriterion("madeDate >=", value, "madeDate");
            return (Criteria) this;
        }

        public Criteria andMadeDateLessThan(Date value) {
            addCriterion("madeDate <", value, "madeDate");
            return (Criteria) this;
        }

        public Criteria andMadeDateLessThanOrEqualTo(Date value) {
            addCriterion("madeDate <=", value, "madeDate");
            return (Criteria) this;
        }

        public Criteria andMadeDateIn(List<Date> values) {
            addCriterion("madeDate in", values, "madeDate");
            return (Criteria) this;
        }

        public Criteria andMadeDateNotIn(List<Date> values) {
            addCriterion("madeDate not in", values, "madeDate");
            return (Criteria) this;
        }

        public Criteria andMadeDateBetween(Date value1, Date value2) {
            addCriterion("madeDate between", value1, value2, "madeDate");
            return (Criteria) this;
        }

        public Criteria andMadeDateNotBetween(Date value1, Date value2) {
            addCriterion("madeDate not between", value1, value2, "madeDate");
            return (Criteria) this;
        }

        public Criteria andMadeByIsNull() {
            addCriterion("madeBy is null");
            return (Criteria) this;
        }

        public Criteria andMadeByIsNotNull() {
            addCriterion("madeBy is not null");
            return (Criteria) this;
        }

        public Criteria andMadeByEqualTo(Integer value) {
            addCriterion("madeBy =", value, "madeBy");
            return (Criteria) this;
        }

        public Criteria andMadeByNotEqualTo(Integer value) {
            addCriterion("madeBy <>", value, "madeBy");
            return (Criteria) this;
        }

        public Criteria andMadeByGreaterThan(Integer value) {
            addCriterion("madeBy >", value, "madeBy");
            return (Criteria) this;
        }

        public Criteria andMadeByGreaterThanOrEqualTo(Integer value) {
            addCriterion("madeBy >=", value, "madeBy");
            return (Criteria) this;
        }

        public Criteria andMadeByLessThan(Integer value) {
            addCriterion("madeBy <", value, "madeBy");
            return (Criteria) this;
        }

        public Criteria andMadeByLessThanOrEqualTo(Integer value) {
            addCriterion("madeBy <=", value, "madeBy");
            return (Criteria) this;
        }

        public Criteria andMadeByIn(List<Integer> values) {
            addCriterion("madeBy in", values, "madeBy");
            return (Criteria) this;
        }

        public Criteria andMadeByNotIn(List<Integer> values) {
            addCriterion("madeBy not in", values, "madeBy");
            return (Criteria) this;
        }

        public Criteria andMadeByBetween(Integer value1, Integer value2) {
            addCriterion("madeBy between", value1, value2, "madeBy");
            return (Criteria) this;
        }

        public Criteria andMadeByNotBetween(Integer value1, Integer value2) {
            addCriterion("madeBy not between", value1, value2, "madeBy");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Reservation
     *
     * @mbg.generated do_not_delete_during_merge Mon Aug 06 09:49:26 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Reservation
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}