package cn.scau.pojo;

import java.sql.Date;

public class Reservation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Reservation.confirmID
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    private Integer confirmID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Reservation.ciDate
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    private Date ciDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Reservation.coDate
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    private Date coDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Reservation.adults
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    private Integer adults;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Reservation.child
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    private Integer child;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Reservation.quantity
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Reservation.rmType
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    private String rmType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Reservation.rateType
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    private String rateType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Reservation.amount
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    private Double amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Reservation.title1
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    private String title1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Reservation.name1
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    private String name1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Reservation.surname1
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    private String surname1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Reservation.title12
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    private String title12;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Reservation.name2
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    private String name2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Reservation.surname2
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    private String surname2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Reservation.city
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Reservation.zip
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    private String zip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Reservation.country
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Reservation.phone
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Reservation.cardType
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    private String cardType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Reservation.cardNumber
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    private String cardNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Reservation.cardExpire
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    private String cardExpire;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Reservation.status
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Reservation.freeCancelDate
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    private java.sql.Date freeCancelDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Reservation.rsvFrom
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    private String rsvFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Reservation.madeDate
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    private java.sql.Date madeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Reservation.madeBy
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    private Integer madeBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Reservation.confirmID
     *
     * @return the value of Reservation.confirmID
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public Integer getConfirmID() {
        return confirmID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Reservation.confirmID
     *
     * @param confirmID the value for Reservation.confirmID
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public void setConfirmID(Integer confirmID) {
        this.confirmID = confirmID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Reservation.ciDate
     *
     * @return the value of Reservation.ciDate
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public Date getCiDate() {
        return ciDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Reservation.ciDate
     *
     * @param ciDate the value for Reservation.ciDate
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public void setCiDate(Date ciDate) {
        this.ciDate = ciDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Reservation.coDate
     *
     * @return the value of Reservation.coDate
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public Date getCoDate() {
        return coDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Reservation.coDate
     *
     * @param coDate the value for Reservation.coDate
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public void setCoDate(Date coDate) {
        this.coDate = coDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Reservation.adults
     *
     * @return the value of Reservation.adults
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public Integer getAdults() {
        return adults;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Reservation.adults
     *
     * @param adults the value for Reservation.adults
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public void setAdults(Integer adults) {
        this.adults = adults;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Reservation.child
     *
     * @return the value of Reservation.child
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public Integer getChild() {
        return child;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Reservation.child
     *
     * @param child the value for Reservation.child
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public void setChild(Integer child) {
        this.child = child;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Reservation.quantity
     *
     * @return the value of Reservation.quantity
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Reservation.quantity
     *
     * @param quantity the value for Reservation.quantity
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Reservation.rmType
     *
     * @return the value of Reservation.rmType
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public String getRmType() {
        return rmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Reservation.rmType
     *
     * @param rmType the value for Reservation.rmType
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public void setRmType(String rmType) {
        this.rmType = rmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Reservation.rateType
     *
     * @return the value of Reservation.rateType
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public String getRateType() {
        return rateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Reservation.rateType
     *
     * @param rateType the value for Reservation.rateType
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public void setRateType(String rateType) {
        this.rateType = rateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Reservation.amount
     *
     * @return the value of Reservation.amount
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Reservation.amount
     *
     * @param amount the value for Reservation.amount
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Reservation.title1
     *
     * @return the value of Reservation.title1
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public String getTitle1() {
        return title1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Reservation.title1
     *
     * @param title1 the value for Reservation.title1
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public void setTitle1(String title1) {
        this.title1 = title1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Reservation.name1
     *
     * @return the value of Reservation.name1
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public String getName1() {
        return name1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Reservation.name1
     *
     * @param name1 the value for Reservation.name1
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public void setName1(String name1) {
        this.name1 = name1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Reservation.surname1
     *
     * @return the value of Reservation.surname1
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public String getSurname1() {
        return surname1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Reservation.surname1
     *
     * @param surname1 the value for Reservation.surname1
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public void setSurname1(String surname1) {
        this.surname1 = surname1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Reservation.title12
     *
     * @return the value of Reservation.title12
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public String getTitle12() {
        return title12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Reservation.title12
     *
     * @param title12 the value for Reservation.title12
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public void setTitle12(String title12) {
        this.title12 = title12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Reservation.name2
     *
     * @return the value of Reservation.name2
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public String getName2() {
        return name2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Reservation.name2
     *
     * @param name2 the value for Reservation.name2
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public void setName2(String name2) {
        this.name2 = name2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Reservation.surname2
     *
     * @return the value of Reservation.surname2
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public String getSurname2() {
        return surname2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Reservation.surname2
     *
     * @param surname2 the value for Reservation.surname2
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public void setSurname2(String surname2) {
        this.surname2 = surname2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Reservation.city
     *
     * @return the value of Reservation.city
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Reservation.city
     *
     * @param city the value for Reservation.city
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Reservation.zip
     *
     * @return the value of Reservation.zip
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public String getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Reservation.zip
     *
     * @param zip the value for Reservation.zip
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public void setZip(String zip) {
        this.zip = zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Reservation.country
     *
     * @return the value of Reservation.country
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Reservation.country
     *
     * @param country the value for Reservation.country
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Reservation.phone
     *
     * @return the value of Reservation.phone
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Reservation.phone
     *
     * @param phone the value for Reservation.phone
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Reservation.cardType
     *
     * @return the value of Reservation.cardType
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public String getCardType() {
        return cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Reservation.cardType
     *
     * @param cardType the value for Reservation.cardType
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public void setCardType(String cardType) {
        this.cardType = cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Reservation.cardNumber
     *
     * @return the value of Reservation.cardNumber
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public String getCardNumber() {
        return cardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Reservation.cardNumber
     *
     * @param cardNumber the value for Reservation.cardNumber
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Reservation.cardExpire
     *
     * @return the value of Reservation.cardExpire
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public String getCardExpire() {
        return cardExpire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Reservation.cardExpire
     *
     * @param cardExpire the value for Reservation.cardExpire
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public void setCardExpire(String cardExpire) {
        this.cardExpire = cardExpire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Reservation.status
     *
     * @return the value of Reservation.status
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Reservation.status
     *
     * @param status the value for Reservation.status
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Reservation.freeCancelDate
     *
     * @return the value of Reservation.freeCancelDate
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public Date getFreeCancelDate() {
        return freeCancelDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Reservation.freeCancelDate
     *
     * @param freeCancelDate the value for Reservation.freeCancelDate
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public void setFreeCancelDate(java.sql.Date freeCancelDate) {
        this.freeCancelDate = freeCancelDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Reservation.rsvFrom
     *
     * @return the value of Reservation.rsvFrom
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public String getRsvFrom() {
        return rsvFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Reservation.rsvFrom
     *
     * @param rsvFrom the value for Reservation.rsvFrom
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public void setRsvFrom(String rsvFrom) {
        this.rsvFrom = rsvFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Reservation.madeDate
     *
     * @return the value of Reservation.madeDate
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public Date getMadeDate() {
        return madeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Reservation.madeDate
     *
     * @param madeDate the value for Reservation.madeDate
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public void setMadeDate(java.sql.Date madeDate) {
        this.madeDate = madeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Reservation.madeBy
     *
     * @return the value of Reservation.madeBy
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public Integer getMadeBy() {
        return madeBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Reservation.madeBy
     *
     * @param madeBy the value for Reservation.madeBy
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public void setMadeBy(Integer madeBy) {
        this.madeBy = madeBy;
    }
}