package cn.scau.pojo;

public class ReservationWithBLOBs extends Reservation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Reservation.address
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Reservation.notes
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    private String notes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Reservation.address
     *
     * @return the value of Reservation.address
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Reservation.address
     *
     * @param address the value for Reservation.address
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Reservation.notes
     *
     * @return the value of Reservation.notes
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Reservation.notes
     *
     * @param notes the value for Reservation.notes
     *
     * @mbg.generated Mon Aug 06 09:49:26 CST 2018
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }
}