package cn.scau.pojo;

import java.sql.Date;

public class RoomRule {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RoomRule.id
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RoomRule.fromDate
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	private Date fromDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RoomRule.toDate
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	private Date toDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RoomRule.rmType
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	private String rmType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RoomRule.num
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	private Integer num;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RoomRule.notes
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	private String notes;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RoomRule.id
	 * @return  the value of RoomRule.id
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RoomRule.id
	 * @param id  the value for RoomRule.id
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RoomRule.fromDate
	 * @return  the value of RoomRule.fromDate
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public Date getFromDate() {
		return fromDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RoomRule.fromDate
	 * @param fromDate  the value for RoomRule.fromDate
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RoomRule.toDate
	 * @return  the value of RoomRule.toDate
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public Date getToDate() {
		return toDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RoomRule.toDate
	 * @param toDate  the value for RoomRule.toDate
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RoomRule.rmType
	 * @return  the value of RoomRule.rmType
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public String getRmType() {
		return rmType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RoomRule.rmType
	 * @param rmType  the value for RoomRule.rmType
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public void setRmType(String rmType) {
		this.rmType = rmType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RoomRule.num
	 * @return  the value of RoomRule.num
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public Integer getNum() {
		return num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RoomRule.num
	 * @param num  the value for RoomRule.num
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public void setNum(Integer num) {
		this.num = num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RoomRule.notes
	 * @return  the value of RoomRule.notes
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public String getNotes() {
		return notes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RoomRule.notes
	 * @param notes  the value for RoomRule.notes
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public void setNotes(String notes) {
		this.notes = notes;
	}
}