package cn.scau.pojo;

public class Staff {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Staff.id
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Staff.pd
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	private String pd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Staff.name
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Staff.surname
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	private String surname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Staff.dept
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	private String dept;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Staff.position
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	private String position;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Staff.notes
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	private String notes;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Staff.id
	 * @return  the value of Staff.id
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Staff.id
	 * @param id  the value for Staff.id
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Staff.pd
	 * @return  the value of Staff.pd
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public String getPd() {
		return pd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Staff.pd
	 * @param pd  the value for Staff.pd
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public void setPd(String pd) {
		this.pd = pd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Staff.name
	 * @return  the value of Staff.name
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Staff.name
	 * @param name  the value for Staff.name
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Staff.surname
	 * @return  the value of Staff.surname
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public String getSurname() {
		return surname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Staff.surname
	 * @param surname  the value for Staff.surname
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public void setSurname(String surname) {
		this.surname = surname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Staff.dept
	 * @return  the value of Staff.dept
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public String getDept() {
		return dept;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Staff.dept
	 * @param dept  the value for Staff.dept
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public void setDept(String dept) {
		this.dept = dept;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Staff.position
	 * @return  the value of Staff.position
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public String getPosition() {
		return position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Staff.position
	 * @param position  the value for Staff.position
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public void setPosition(String position) {
		this.position = position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Staff.notes
	 * @return  the value of Staff.notes
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public String getNotes() {
		return notes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Staff.notes
	 * @param notes  the value for Staff.notes
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public void setNotes(String notes) {
		this.notes = notes;
	}
}