package cn.scau.pojo;

import java.util.ArrayList;
import java.util.List;

public class StaffExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table Staff
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table Staff
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table Staff
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Staff
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public StaffExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Staff
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Staff
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Staff
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Staff
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Staff
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Staff
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Staff
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Staff
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Staff
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Staff
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table Staff
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andPdIsNull() {
			addCriterion("pd is null");
			return (Criteria) this;
		}

		public Criteria andPdIsNotNull() {
			addCriterion("pd is not null");
			return (Criteria) this;
		}

		public Criteria andPdEqualTo(String value) {
			addCriterion("pd =", value, "pd");
			return (Criteria) this;
		}

		public Criteria andPdNotEqualTo(String value) {
			addCriterion("pd <>", value, "pd");
			return (Criteria) this;
		}

		public Criteria andPdGreaterThan(String value) {
			addCriterion("pd >", value, "pd");
			return (Criteria) this;
		}

		public Criteria andPdGreaterThanOrEqualTo(String value) {
			addCriterion("pd >=", value, "pd");
			return (Criteria) this;
		}

		public Criteria andPdLessThan(String value) {
			addCriterion("pd <", value, "pd");
			return (Criteria) this;
		}

		public Criteria andPdLessThanOrEqualTo(String value) {
			addCriterion("pd <=", value, "pd");
			return (Criteria) this;
		}

		public Criteria andPdLike(String value) {
			addCriterion("pd like", value, "pd");
			return (Criteria) this;
		}

		public Criteria andPdNotLike(String value) {
			addCriterion("pd not like", value, "pd");
			return (Criteria) this;
		}

		public Criteria andPdIn(List<String> values) {
			addCriterion("pd in", values, "pd");
			return (Criteria) this;
		}

		public Criteria andPdNotIn(List<String> values) {
			addCriterion("pd not in", values, "pd");
			return (Criteria) this;
		}

		public Criteria andPdBetween(String value1, String value2) {
			addCriterion("pd between", value1, value2, "pd");
			return (Criteria) this;
		}

		public Criteria andPdNotBetween(String value1, String value2) {
			addCriterion("pd not between", value1, value2, "pd");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andSurnameIsNull() {
			addCriterion("surname is null");
			return (Criteria) this;
		}

		public Criteria andSurnameIsNotNull() {
			addCriterion("surname is not null");
			return (Criteria) this;
		}

		public Criteria andSurnameEqualTo(String value) {
			addCriterion("surname =", value, "surname");
			return (Criteria) this;
		}

		public Criteria andSurnameNotEqualTo(String value) {
			addCriterion("surname <>", value, "surname");
			return (Criteria) this;
		}

		public Criteria andSurnameGreaterThan(String value) {
			addCriterion("surname >", value, "surname");
			return (Criteria) this;
		}

		public Criteria andSurnameGreaterThanOrEqualTo(String value) {
			addCriterion("surname >=", value, "surname");
			return (Criteria) this;
		}

		public Criteria andSurnameLessThan(String value) {
			addCriterion("surname <", value, "surname");
			return (Criteria) this;
		}

		public Criteria andSurnameLessThanOrEqualTo(String value) {
			addCriterion("surname <=", value, "surname");
			return (Criteria) this;
		}

		public Criteria andSurnameLike(String value) {
			addCriterion("surname like", value, "surname");
			return (Criteria) this;
		}

		public Criteria andSurnameNotLike(String value) {
			addCriterion("surname not like", value, "surname");
			return (Criteria) this;
		}

		public Criteria andSurnameIn(List<String> values) {
			addCriterion("surname in", values, "surname");
			return (Criteria) this;
		}

		public Criteria andSurnameNotIn(List<String> values) {
			addCriterion("surname not in", values, "surname");
			return (Criteria) this;
		}

		public Criteria andSurnameBetween(String value1, String value2) {
			addCriterion("surname between", value1, value2, "surname");
			return (Criteria) this;
		}

		public Criteria andSurnameNotBetween(String value1, String value2) {
			addCriterion("surname not between", value1, value2, "surname");
			return (Criteria) this;
		}

		public Criteria andDeptIsNull() {
			addCriterion("dept is null");
			return (Criteria) this;
		}

		public Criteria andDeptIsNotNull() {
			addCriterion("dept is not null");
			return (Criteria) this;
		}

		public Criteria andDeptEqualTo(String value) {
			addCriterion("dept =", value, "dept");
			return (Criteria) this;
		}

		public Criteria andDeptNotEqualTo(String value) {
			addCriterion("dept <>", value, "dept");
			return (Criteria) this;
		}

		public Criteria andDeptGreaterThan(String value) {
			addCriterion("dept >", value, "dept");
			return (Criteria) this;
		}

		public Criteria andDeptGreaterThanOrEqualTo(String value) {
			addCriterion("dept >=", value, "dept");
			return (Criteria) this;
		}

		public Criteria andDeptLessThan(String value) {
			addCriterion("dept <", value, "dept");
			return (Criteria) this;
		}

		public Criteria andDeptLessThanOrEqualTo(String value) {
			addCriterion("dept <=", value, "dept");
			return (Criteria) this;
		}

		public Criteria andDeptLike(String value) {
			addCriterion("dept like", value, "dept");
			return (Criteria) this;
		}

		public Criteria andDeptNotLike(String value) {
			addCriterion("dept not like", value, "dept");
			return (Criteria) this;
		}

		public Criteria andDeptIn(List<String> values) {
			addCriterion("dept in", values, "dept");
			return (Criteria) this;
		}

		public Criteria andDeptNotIn(List<String> values) {
			addCriterion("dept not in", values, "dept");
			return (Criteria) this;
		}

		public Criteria andDeptBetween(String value1, String value2) {
			addCriterion("dept between", value1, value2, "dept");
			return (Criteria) this;
		}

		public Criteria andDeptNotBetween(String value1, String value2) {
			addCriterion("dept not between", value1, value2, "dept");
			return (Criteria) this;
		}

		public Criteria andPositionIsNull() {
			addCriterion("position is null");
			return (Criteria) this;
		}

		public Criteria andPositionIsNotNull() {
			addCriterion("position is not null");
			return (Criteria) this;
		}

		public Criteria andPositionEqualTo(String value) {
			addCriterion("position =", value, "position");
			return (Criteria) this;
		}

		public Criteria andPositionNotEqualTo(String value) {
			addCriterion("position <>", value, "position");
			return (Criteria) this;
		}

		public Criteria andPositionGreaterThan(String value) {
			addCriterion("position >", value, "position");
			return (Criteria) this;
		}

		public Criteria andPositionGreaterThanOrEqualTo(String value) {
			addCriterion("position >=", value, "position");
			return (Criteria) this;
		}

		public Criteria andPositionLessThan(String value) {
			addCriterion("position <", value, "position");
			return (Criteria) this;
		}

		public Criteria andPositionLessThanOrEqualTo(String value) {
			addCriterion("position <=", value, "position");
			return (Criteria) this;
		}

		public Criteria andPositionLike(String value) {
			addCriterion("position like", value, "position");
			return (Criteria) this;
		}

		public Criteria andPositionNotLike(String value) {
			addCriterion("position not like", value, "position");
			return (Criteria) this;
		}

		public Criteria andPositionIn(List<String> values) {
			addCriterion("position in", values, "position");
			return (Criteria) this;
		}

		public Criteria andPositionNotIn(List<String> values) {
			addCriterion("position not in", values, "position");
			return (Criteria) this;
		}

		public Criteria andPositionBetween(String value1, String value2) {
			addCriterion("position between", value1, value2, "position");
			return (Criteria) this;
		}

		public Criteria andPositionNotBetween(String value1, String value2) {
			addCriterion("position not between", value1, value2, "position");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table Staff
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Staff
     *
     * @mbg.generated do_not_delete_during_merge Wed Aug 01 16:04:16 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}