package cn.scau.dao;

import cn.scau.pojo.DailyStatus;
import cn.scau.pojo.DailyStatusExample;
import cn.scau.pojo.DailyStatusKey;
import java.util.List;

public interface DailyStatusMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DailyStatus
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	int deleteByPrimaryKey(DailyStatusKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DailyStatus
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	int insert(DailyStatus record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DailyStatus
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	int insertSelective(DailyStatus record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DailyStatus
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	List<DailyStatus> selectByExample(DailyStatusExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DailyStatus
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	DailyStatus selectByPrimaryKey(DailyStatusKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DailyStatus
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	int updateByPrimaryKeySelective(DailyStatus record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DailyStatus
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	int updateByPrimaryKey(DailyStatus record);
}