package cn.scau.dao;

import cn.scau.pojo.DS;
import cn.scau.pojo.DSExample;
import java.util.List;

public interface DSMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds
     *
     * @mbg.generated Wed Aug 08 13:23:44 CST 2018
     */
    long countByExample(DSExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds
     *
     * @mbg.generated Wed Aug 08 13:23:44 CST 2018
     */
    int insert(DS record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds
     *
     * @mbg.generated Wed Aug 08 13:23:44 CST 2018
     */
    int insertSelective(DS record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ds
     *
     * @mbg.generated Wed Aug 08 13:23:44 CST 2018
     */
    List<DS> selectByExample(DSExample example);
}