package cn.scau.dao;

import cn.scau.page.Page;
import cn.scau.pojo.RateRule;
import cn.scau.pojo.RateRuleExample;
import cn.scau.pojo.RateRule;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface RateRuleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RateRule
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RateRule
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	int insert(RateRule record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RateRule
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	int insertSelective(RateRule record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RateRule
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	List<RateRule> selectByExampleWithBLOBs(RateRuleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RateRule
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	List<RateRule> selectByExample(RateRuleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RateRule
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	RateRule selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RateRule
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	int updateByPrimaryKeySelective(RateRule record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RateRule
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	int updateByPrimaryKeyWithBLOBs(RateRule record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RateRule
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	int updateByPrimaryKey(RateRule record);
	
	List<RateRule> list(@Param("page") Page page, @Param("record") RateRule record);
    
    int total(@Param("record") RateRule record);
}