package cn.scau.dao;

import cn.scau.page.Page;
import cn.scau.pojo.RoomRule;
import cn.scau.pojo.RoomRule;
import cn.scau.pojo.RoomRuleExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface RoomRuleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RoomRule
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RoomRule
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	int insert(RoomRule record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RoomRule
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	int insertSelective(RoomRule record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RoomRule
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	List<RoomRule> selectByExampleWithBLOBs(RoomRuleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RoomRule
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	List<RoomRule> selectByExample(RoomRuleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RoomRule
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	RoomRule selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RoomRule
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	int updateByPrimaryKeySelective(RoomRule record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RoomRule
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	int updateByPrimaryKeyWithBLOBs(RoomRule record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RoomRule
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	int updateByPrimaryKey(RoomRule record);
	
	List<RoomRule> list(@Param("page") Page page, @Param("record") RoomRule record);
    
    int total(@Param("record") RoomRule record);
}