package cn.scau.dao;

import cn.scau.page.Page;
import cn.scau.pojo.Staff;
import cn.scau.pojo.Staff;
import cn.scau.pojo.StaffExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface StaffMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Staff
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Staff
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	int insert(Staff record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Staff
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	int insertSelective(Staff record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Staff
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	List<Staff> selectByExampleWithBLOBs(StaffExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Staff
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	List<Staff> selectByExample(StaffExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Staff
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	Staff selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Staff
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	int updateByPrimaryKeySelective(Staff record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Staff
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	int updateByPrimaryKeyWithBLOBs(Staff record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Staff
	 * @mbg.generated  Sat Aug 04 20:04:16 CST 2018
	 */
	int updateByPrimaryKey(Staff record);

	Staff checkStaff (@Param("name") String name, @Param("pd") String pd);
	List<Staff> list(@Param("page") Page page, @Param("record") Staff record);
    
    int total(@Param("record") Staff record);
}